In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv("gpu_1986-2026.csv", usecols=["Brand", "Name", "Graphics Card__Release Date", "Memory__Memory Size"])
df.head()

,Brand,Name,Graphics Card__Release Date,Memory__Memory Size
0,ATI,Color Emulation Card,"Aug 4th, 1986",32 KB
1,ATI,Graphics Solution,"Sep 22nd, 1986",64 KB
2,ATI,EGA Wonder 800,"Nov 16th, 1987",256 KB
3,ATI,Graphics Solution Plus,"Mar 23rd, 1987",64 KB
4,ATI,VGA Improved Performance,"Sep 28th, 1987",256 KB

In [3]:
df.tail()

     Brand             Name Graphics Card__Release Date Memory__Memory Size
3198   XGI  Volari V5 Ultra              Sep 15th, 2003              256 MB
3199   XGI        Volari V8              Sep 15th, 2003              256 MB
3200   XGI        Volari V8              Sep 15th, 2003              256 MB
3201   XGI  Volari V8 Ultra              Sep 15th, 2003              256 MB
3202   XGI  Volari V8 Ultra              Sep 15th, 2003              256 MB

In [7]:
column_namechange = {
    "Graphics Card__Release Date": "Date",
    "Memory__Memory Size": "Memory"
}

for old, new in column_namechange.items():
    df[new] = df[old]
    df = df.drop(columns=[old])
df

     Brand                      Name            Date  Memory
0      ATI      Color Emulation Card   Aug 4th, 1986   32 KB
1      ATI         Graphics Solution  Sep 22nd, 1986   64 KB
2      ATI            EGA Wonder 800  Nov 16th, 1987  256 KB
3      ATI    Graphics Solution Plus  Mar 23rd, 1987   64 KB
4      ATI  VGA Improved Performance  Sep 28th, 1987  256 KB
...    ...                       ...             ...     ...
3198   XGI           Volari V5 Ultra  Sep 15th, 2003  256 MB
3199   XGI                 Volari V8  Sep 15th, 2003  256 MB
3200   XGI                 Volari V8  Sep 15th, 2003  256 MB
3201   XGI           Volari V8 Ultra  Sep 15th, 2003  256 MB
3202   XGI           Volari V8 Ultra  Sep 15th, 2003  256 MB

[3203 rows x 4 columns]

In [ ]:
mem_value = df["Memory"].str.extract(r"(\d+)").astype("float")
mem_unit = df["Memory"].str.extract(r"(KB|MB|GB)")